/* See LICENSE file for copyright and license details. */
#ifdef __APPLE__
#define _DARWIN_C_SOURCE 1

#import <Cocoa/Cocoa.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <signal.h>
#include "clipbridge.h"
#include "unipaste.h"

static volatile sig_atomic_t running = 1;

static void
sig_handler(int sig)
{
	(void)sig;
	running = 0;
}

/* Check if clipboard is marked concealed/private by password managers */
static int
is_clipboard_concealed(NSPasteboard *pboard)
{
	NSPasteboardType concealedType = @"org.nspasteboard.ConcealedType";
	NSPasteboardType autoGeneratedType = @"org.nspasteboard.AutoGeneratedType";

	NSArray *types = [pboard types];
	if ([types containsObject:concealedType] || [types containsObject:autoGeneratedType]) {
		return 1;
	}
	return 0;
}

int
clipboard_read_html(char **out_html, size_t *out_len)
{
	@autoreleasepool {
		NSPasteboard *pboard = [NSPasteboard generalPasteboard];
		*out_html = NULL;
		*out_len = 0;

		if (is_clipboard_concealed(pboard))
			return -1;

		NSPasteboardType htmlType = NSPasteboardTypeHTML;
		if (![[pboard types] containsObject:htmlType])
			return -1;

		NSString *htmlStr = [pboard stringForType:htmlType];
		if (!htmlStr || [htmlStr length] == 0)
			return -1;

		const char *utf8 = [htmlStr UTF8String];
		if (!utf8)
			return -1;

		size_t len = strlen(utf8);
		*out_html = malloc(len + 1);
		if (!*out_html)
			return -1;

		memcpy(*out_html, utf8, len + 1);
		*out_len = len;
		return 0;
	}
}

int
clipboard_write_text(const char *text, size_t len)
{
	if (!text || len == 0)
		return 0;

	@autoreleasepool {
		NSPasteboard *pboard = [NSPasteboard generalPasteboard];
		NSString *str = [[NSString alloc] initWithBytes:text length:len encoding:NSUTF8StringEncoding];
		if (!str)
			return -1;

		/* Update plain-text representation */
		[pboard setString:str forType:NSPasteboardTypeString];
		return 0;
	}
}

static int
process_html_to_clipboard(const char *html, size_t len, const struct config *cfg)
{
	struct strbuf sb;
	int ret;

	strbuf_init(&sb, len * 2);
	ret = unipaste_process_to_strbuf(html, len, &sb, cfg);
	if (ret == 0 && sb.len > 0) {
		clipboard_write_text(sb.data, sb.len);
	}
	strbuf_free(&sb);
	return ret;
}

int
clipboard_sync_once(const struct config *cfg)
{
	char *html = NULL;
	size_t len = 0;
	int ret;

	if (clipboard_read_html(&html, &len) != 0 || !html || len == 0)
		return 1;

	ret = process_html_to_clipboard(html, len, cfg);
	free(html);
	return ret;
}

int
clipboard_paste_stdout(const struct config *cfg)
{
	char *html = NULL;
	size_t len = 0;
	int ret;

	if (clipboard_read_html(&html, &len) != 0 || !html || len == 0) {
		fprintf(stderr, "clipbridge: no rich text/html found on clipboard\n");
		return 1;
	}

	ret = unipaste_process_string(html, len, stdout, cfg);
	free(html);
	return ret;
}

int
clipboard_paste_active(const struct config *cfg)
{
	int ret = clipboard_sync_once(cfg);
	if (ret != 0)
		return ret;

	/* Synthesize Cmd+V keystroke using AppleScript */
	system("osascript -e 'tell application \"System Events\" to keystroke \"v\" using command down' 2>/dev/null");
	return 0;
}

int
clipboard_watch(const struct config *cfg)
{
	struct sigaction sa;
	NSInteger last_change;

	memset(&sa, 0, sizeof(sa));
	sa.sa_handler = sig_handler;
	sigaction(SIGINT, &sa, NULL);
	sigaction(SIGTERM, &sa, NULL);

	printf("clipbridge: monitoring macOS pasteboard (press Ctrl+C to stop)...\n");
	fflush(stdout);

	@autoreleasepool {
		last_change = [[NSPasteboard generalPasteboard] changeCount];
	}

	while (running) {
		@autoreleasepool {
			NSPasteboard *pboard = [NSPasteboard generalPasteboard];
			NSInteger cur_change = [pboard changeCount];

			if (cur_change != last_change) {
				last_change = cur_change;

				char *html = NULL;
				size_t len = 0;
				if (clipboard_read_html(&html, &len) == 0 && html && len > 0) {
					process_html_to_clipboard(html, len, cfg);
					last_change = [pboard changeCount];
					printf("clipbridge: [synced] formatted %zu bytes of rich text -> plain text\n", len);
					fflush(stdout);
					free(html);
				}
			}
		}

		usleep(250000); /* 250ms check interval */
	}

	printf("\nclipbridge: stopped cleanly.\n");
	return 0;
}

#else
typedef int iso_c_dummy_clipbridge_macos;
#endif /* __APPLE__ */
