/* See LICENSE file for copyright and license details. */
#ifdef __APPLE__
#define _DARWIN_C_SOURCE 1

#import <Cocoa/Cocoa.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <signal.h>
#include "clipbridge.h"
#include "unipaste.h"
#include "i18n.h"

static struct config current_cfg;
static BOOL auto_format_default = NO;
static NSInteger last_change = 0;

/* Check if clipboard is marked concealed/private by password managers */
static int
is_clipboard_concealed(NSPasteboard *pboard)
{
	NSPasteboardType concealedType = @"org.nspasteboard.ConcealedType";
	NSPasteboardType autoGeneratedType = @"org.nspasteboard.AutoGeneratedType";

	NSArray *types = [pboard types];
	if ([types containsObject:concealedType] || [types containsObject:autoGeneratedType]) {
		return 1;
	}
	return 0;
}

int
clipboard_read_html(char **out_html, size_t *out_len)
{
	@autoreleasepool {
		NSPasteboard *pboard = [NSPasteboard generalPasteboard];
		*out_html = NULL;
		*out_len = 0;

		if (is_clipboard_concealed(pboard))
			return -1;

		NSPasteboardType htmlType = NSPasteboardTypeHTML;
		if (![[pboard types] containsObject:htmlType])
			return -1;

		NSString *htmlStr = [pboard stringForType:htmlType];
		if (!htmlStr || [htmlStr length] == 0)
			return -1;

		const char *utf8 = [htmlStr UTF8String];
		if (!utf8)
			return -1;

		size_t len = strlen(utf8);
		*out_html = malloc(len + 1);
		if (!*out_html)
			return -1;

		memcpy(*out_html, utf8, len + 1);
		*out_len = len;
		return 0;
	}
}

int
clipboard_write_text(const char *text, size_t len)
{
	if (!text || len == 0)
		return 0;

	@autoreleasepool {
		NSPasteboard *pboard = [NSPasteboard generalPasteboard];
		NSString *str = [[NSString alloc] initWithBytes:text length:len encoding:NSUTF8StringEncoding];
		if (!str)
			return -1;

		/* Update plain-text representation */
		[pboard setString:str forType:NSPasteboardTypeString];
		return 0;
	}
}

static int
process_html_to_clipboard(const char *html, size_t len, const struct config *cfg)
{
	struct strbuf sb;
	int ret;

	strbuf_init(&sb, len * 2);
	ret = unipaste_process_to_strbuf(html, len, &sb, cfg);
	if (ret == 0 && sb.len > 0) {
		clipboard_write_text(sb.data, sb.len);
	}
	strbuf_free(&sb);
	return ret;
}

int
clipboard_sync_once(const struct config *cfg)
{
	char *html = NULL;
	size_t len = 0;
	int ret;

	if (clipboard_read_html(&html, &len) != 0 || !html || len == 0)
		return 1;

	ret = process_html_to_clipboard(html, len, cfg);
	free(html);
	return ret;
}

int
clipboard_paste_stdout(const struct config *cfg)
{
	char *html = NULL;
	size_t len = 0;
	int ret;

	if (clipboard_read_html(&html, &len) != 0 || !html || len == 0) {
		fprintf(stderr, "clipbridge: no rich text/html found on clipboard\n");
		return 1;
	}

	ret = unipaste_process_string(html, len, stdout, cfg);
	free(html);
	return ret;
}

int
clipboard_paste_active(const struct config *cfg)
{
	int ret = clipboard_sync_once(cfg);
	if (ret != 0)
		return ret;

	/* Synthesize Cmd+V keystroke using AppleScript */
	system("osascript -e 'tell application \"System Events\" to keystroke \"v\" using command down' 2>/dev/null");
	return 0;
}

static BOOL
is_launch_agent_enabled(void)
{
	NSString *path = [@"~/Library/LaunchAgents/com.riccivr.clipbridge.plist" stringByExpandingTildeInPath];
	return [[NSFileManager defaultManager] fileExistsAtPath:path];
}

static void
set_launch_agent_enabled(BOOL enable)
{
	NSString *dir = [@"~/Library/LaunchAgents" stringByExpandingTildeInPath];
	NSString *path = [dir stringByAppendingPathComponent:@"com.riccivr.clipbridge.plist"];

	if (enable) {
		[[NSFileManager defaultManager] createDirectoryAtPath:dir withIntermediateDirectories:YES attributes:nil error:nil];
		NSString *execPath = [[NSBundle mainBundle] executablePath];
		if (!execPath || [execPath length] == 0) {
			execPath = @"/usr/local/bin/clipbridge";
		}
		NSString *plistContent = [NSString stringWithFormat:
			@"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
			@"<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n"
			@"<plist version=\"1.0\">\n"
			@"<dict>\n"
			@"    <key>Label</key>\n"
			@"    <string>com.riccivr.clipbridge</string>\n"
			@"    <key>ProgramArguments</key>\n"
			@"    <array>\n"
			@"        <string>%@</string>\n"
			@"        <string>-w</string>\n"
			@"    </array>\n"
			@"    <key>RunAtLoad</key>\n"
			@"    <true/>\n"
			@"    <key>KeepAlive</key>\n"
			@"    <true/>\n"
			@"</dict>\n"
			@"</plist>\n", execPath];
		[plistContent writeToFile:path atomically:YES encoding:NSUTF8StringEncoding error:nil];
		system([[NSString stringWithFormat:@"launchctl load '%@' 2>/dev/null", path] UTF8String]);
	} else {
		system([[NSString stringWithFormat:@"launchctl unload '%@' 2>/dev/null", path] UTF8String]);
		[[NSFileManager defaultManager] removeItemAtPath:path error:nil];
	}
}

/* Vector status bar template icon (adapts automatically to macOS Dark/Light menu bar) */
static NSImage *
create_status_bar_template_icon(void)
{
	NSString *iconPath = [[NSBundle mainBundle] pathForResource:@"tray_template" ofType:@"png"];
	if (iconPath) {
		NSImage *img = [[NSImage alloc] initWithContentsOfFile:iconPath];
		if (img) {
			[img setTemplate:YES];
			[img setSize:NSMakeSize(18, 18)];
			return img;
		}
	}

	NSImage *img = [NSImage imageWithSize:NSMakeSize(18, 18) flipped:NO drawingHandler:^BOOL(NSRect dstRect) {
		(void)dstRect;
		[[NSColor blackColor] setStroke];
		[[NSColor blackColor] setFill];

		/* Board outline */
		NSBezierPath *board = [NSBezierPath bezierPathWithRoundedRect:NSMakeRect(3.5, 1.5, 11, 14) xRadius:1.5 yRadius:1.5];
		[board setLineWidth:1.5];
		[board stroke];

		/* Clip top */
		NSRectFill(NSMakeRect(6, 13, 6, 2.5));
		NSRectFill(NSMakeRect(7, 14.5, 4, 1.5));

		/* Bridge / text lines */
		NSBezierPath *lines = [NSBezierPath bezierPath];
		[lines moveToPoint:NSMakePoint(5.5, 9.5)];
		[lines lineToPoint:NSMakePoint(12.5, 9.5)];
		[lines moveToPoint:NSMakePoint(5.5, 6.5)];
		[lines lineToPoint:NSMakePoint(12.5, 6.5)];
		[lines moveToPoint:NSMakePoint(5.5, 3.5)];
		[lines lineToPoint:NSMakePoint(10.5, 3.5)];
		[lines setLineWidth:1.2];
		[lines stroke];

		return YES;
	}];
	[img setTemplate:YES];
	return img;
}

@interface ClipBridgeAppDelegate : NSObject <NSApplicationDelegate>
@property (strong, nonatomic) NSStatusItem *statusItem;
@property (strong, nonatomic) NSTimer *pollTimer;
@property (strong, nonatomic) NSMenuItem *autoFormatItem;
@property (strong, nonatomic) NSMenuItem *startupItem;
@end

@implementation ClipBridgeAppDelegate

- (void)applicationDidFinishLaunching:(NSNotification *)notification {
	(void)notification;
	[NSApp setActivationPolicy:NSApplicationActivationPolicyAccessory];

	NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
	if (![defaults boolForKey:@"HasCompletedOnboarding"]) {
		NSAlert *alert = [[NSAlert alloc] init];
		[alert setMessageText:@"ClipBridge Setup / Configuración"];
		[alert setInformativeText:@"Welcome to ClipBridge!\nPlease choose your preferred language:\n\n¡Bienvenido a ClipBridge!\nPor favor elija su idioma preferido:"];
		[alert setAlertStyle:NSAlertStyleInformational];
		[alert addButtonWithTitle:@"English"];
		[alert addButtonWithTitle:@"Español"];
		NSModalResponse resp = [alert runModal];
		if (resp == NSAlertSecondButtonReturn) {
			i18n_set_language(LANG_ES);
			[defaults setObject:@"es" forKey:@"Language"];
		} else {
			i18n_set_language(LANG_EN);
			[defaults setObject:@"en" forKey:@"Language"];
		}
		[defaults setBool:YES forKey:@"HasCompletedOnboarding"];
	} else {
		NSString *savedLang = [defaults stringForKey:@"Language"];
		if ([savedLang isEqualToString:@"es"]) {
			i18n_set_language(LANG_ES);
		} else if ([savedLang isEqualToString:@"en"]) {
			i18n_set_language(LANG_EN);
		} else {
			i18n_init(LANG_AUTO);
		}
	}

	self.statusItem = [[NSStatusBar systemStatusBar] statusItemWithLength:NSSquareStatusItemLength];
	NSStatusBarButton *button = self.statusItem.button;
	if (button) {
		button.image = create_status_bar_template_icon();
		button.toolTip = [NSString stringWithUTF8String:i18n_get(STR_TOOLTIP_ACTIVE)];
	}

	[self buildMenu];

	last_change = [[NSPasteboard generalPasteboard] changeCount];
	self.pollTimer = [NSTimer scheduledTimerWithTimeInterval:0.25 target:self selector:@selector(pollClipboard:) userInfo:nil repeats:YES];
}

- (void)buildMenu {
	NSMenu *menu = [[NSMenu alloc] initWithTitle:@"ClipBridge"];

	/* Paste with ClipBridge */
	NSString *pasteTitle = [NSString stringWithUTF8String:i18n_get(STR_PASTE_ACTIVE)];
	NSMenuItem *pasteItem = [[NSMenuItem alloc] initWithTitle:pasteTitle action:@selector(actionPasteActive:) keyEquivalent:@"v"];
	[pasteItem setKeyEquivalentModifierMask:(NSEventModifierFlagCommand | NSEventModifierFlagOption)];
	[pasteItem setTarget:self];
	[menu addItem:pasteItem];

	[menu addItem:[NSMenuItem separatorItem]];

	/* Auto-format default paste */
	NSString *autoTitle = [NSString stringWithUTF8String:i18n_get(STR_AUTO_FORMAT)];
	self.autoFormatItem = [[NSMenuItem alloc] initWithTitle:autoTitle action:@selector(toggleAutoFormat:) keyEquivalent:@""];
	[self.autoFormatItem setTarget:self];
	[self.autoFormatItem setState:(auto_format_default ? NSControlStateValueOn : NSControlStateValueOff)];
	[menu addItem:self.autoFormatItem];

	[menu addItem:[NSMenuItem separatorItem]];

	/* Mode Submenu */
	NSString *modeTitle = [NSString stringWithUTF8String:i18n_get(STR_OUTPUT_MODE)];
	NSMenuItem *modeParent = [[NSMenuItem alloc] initWithTitle:modeTitle action:nil keyEquivalent:@""];
	NSMenu *modeMenu = [[NSMenu alloc] initWithTitle:modeTitle];
	
	NSMenuItem *mPlain = [[NSMenuItem alloc] initWithTitle:[NSString stringWithUTF8String:i18n_get(STR_MODE_PLAIN)] action:@selector(setModePlain:) keyEquivalent:@""];
	[mPlain setTarget:self];
	[mPlain setState:(current_cfg.mode == MODE_PLAIN ? NSControlStateValueOn : NSControlStateValueOff)];
	[modeMenu addItem:mPlain];

	NSMenuItem *mMarkdown = [[NSMenuItem alloc] initWithTitle:[NSString stringWithUTF8String:i18n_get(STR_MODE_MARKDOWN)] action:@selector(setModeMarkdown:) keyEquivalent:@""];
	[mMarkdown setTarget:self];
	[mMarkdown setState:(current_cfg.mode == MODE_MARKDOWN ? NSControlStateValueOn : NSControlStateValueOff)];
	[modeMenu addItem:mMarkdown];

	NSMenuItem *mTerminal = [[NSMenuItem alloc] initWithTitle:[NSString stringWithUTF8String:i18n_get(STR_MODE_TERMINAL)] action:@selector(setModeTerminal:) keyEquivalent:@""];
	[mTerminal setTarget:self];
	[mTerminal setState:(current_cfg.mode == MODE_TERMINAL ? NSControlStateValueOn : NSControlStateValueOff)];
	[modeMenu addItem:mTerminal];

	[modeParent setSubmenu:modeMenu];
	[menu addItem:modeParent];

	/* Table Submenu */
	NSString *tableTitle = [NSString stringWithUTF8String:i18n_get(STR_TABLE_STYLE)];
	NSMenuItem *tableParent = [[NSMenuItem alloc] initWithTitle:tableTitle action:nil keyEquivalent:@""];
	NSMenu *tableMenu = [[NSMenu alloc] initWithTitle:tableTitle];

	NSMenuItem *tGrid = [[NSMenuItem alloc] initWithTitle:[NSString stringWithUTF8String:i18n_get(STR_TABLE_GRID)] action:@selector(setTableGrid:) keyEquivalent:@""];
	[tGrid setTarget:self];
	[tGrid setState:(current_cfg.table_style == TABLE_STYLE_GRID && !current_cfg.unicode_tables ? NSControlStateValueOn : NSControlStateValueOff)];
	[tableMenu addItem:tGrid];

	NSMenuItem *tUnicode = [[NSMenuItem alloc] initWithTitle:[NSString stringWithUTF8String:i18n_get(STR_TABLE_UNICODE)] action:@selector(setTableUnicode:) keyEquivalent:@""];
	[tUnicode setTarget:self];
	[tUnicode setState:(current_cfg.unicode_tables ? NSControlStateValueOn : NSControlStateValueOff)];
	[tableMenu addItem:tUnicode];

	NSMenuItem *tMd = [[NSMenuItem alloc] initWithTitle:[NSString stringWithUTF8String:i18n_get(STR_TABLE_MARKDOWN)] action:@selector(setTableMarkdown:) keyEquivalent:@""];
	[tMd setTarget:self];
	[tMd setState:(current_cfg.table_style == TABLE_STYLE_MARKDOWN ? NSControlStateValueOn : NSControlStateValueOff)];
	[tableMenu addItem:tMd];

	NSMenuItem *tTsv = [[NSMenuItem alloc] initWithTitle:[NSString stringWithUTF8String:i18n_get(STR_TABLE_TSV)] action:@selector(setTableTsv:) keyEquivalent:@""];
	[tTsv setTarget:self];
	[tTsv setState:(current_cfg.table_style == TABLE_STYLE_TSV ? NSControlStateValueOn : NSControlStateValueOff)];
	[tableMenu addItem:tTsv];

	[tableParent setSubmenu:tableMenu];
	[menu addItem:tableParent];

	/* Language Submenu */
	NSString *langTitle = [NSString stringWithUTF8String:i18n_get(STR_LANGUAGE)];
	NSMenuItem *langParent = [[NSMenuItem alloc] initWithTitle:langTitle action:nil keyEquivalent:@""];
	NSMenu *langMenu = [[NSMenu alloc] initWithTitle:langTitle];

	NSMenuItem *lAuto = [[NSMenuItem alloc] initWithTitle:[NSString stringWithUTF8String:i18n_get(STR_LANG_AUTO)] action:@selector(setLangAuto:) keyEquivalent:@""];
	[lAuto setTarget:self];
	[lAuto setState:(i18n_get_language() == LANG_AUTO ? NSControlStateValueOn : NSControlStateValueOff)];
	[langMenu addItem:lAuto];

	NSMenuItem *lEn = [[NSMenuItem alloc] initWithTitle:[NSString stringWithUTF8String:i18n_get(STR_LANG_EN)] action:@selector(setLangEn:) keyEquivalent:@""];
	[lEn setTarget:self];
	[lEn setState:(i18n_get_language() == LANG_EN ? NSControlStateValueOn : NSControlStateValueOff)];
	[langMenu addItem:lEn];

	NSMenuItem *lEs = [[NSMenuItem alloc] initWithTitle:[NSString stringWithUTF8String:i18n_get(STR_LANG_ES)] action:@selector(setLangEs:) keyEquivalent:@""];
	[lEs setTarget:self];
	[lEs setState:(i18n_get_language() == LANG_ES ? NSControlStateValueOn : NSControlStateValueOff)];
	[langMenu addItem:lEs];

	[langParent setSubmenu:langMenu];
	[menu addItem:langParent];

	[menu addItem:[NSMenuItem separatorItem]];

	/* Start with macOS Login */
	NSString *startTitle = [NSString stringWithUTF8String:i18n_get(STR_STARTUP)];
	self.startupItem = [[NSMenuItem alloc] initWithTitle:startTitle action:@selector(toggleStartup:) keyEquivalent:@""];
	[self.startupItem setTarget:self];
	[self.startupItem setState:(is_launch_agent_enabled() ? NSControlStateValueOn : NSControlStateValueOff)];
	[menu addItem:self.startupItem];

	/* About ClipBridge */
	NSString *aboutTitle = [NSString stringWithUTF8String:i18n_get(STR_ABOUT_MENU)];
	NSMenuItem *aboutItem = [[NSMenuItem alloc] initWithTitle:aboutTitle action:@selector(showAbout:) keyEquivalent:@""];
	[aboutItem setTarget:self];
	[menu addItem:aboutItem];

	[menu addItem:[NSMenuItem separatorItem]];

	/* Quit */
	NSString *quitTitle = [NSString stringWithUTF8String:i18n_get(STR_EXIT)];
	NSMenuItem *quitItem = [[NSMenuItem alloc] initWithTitle:quitTitle action:@selector(quitApp:) keyEquivalent:@"q"];
	[quitItem setTarget:self];
	[menu addItem:quitItem];

	self.statusItem.menu = menu;
}

- (void)pollClipboard:(NSTimer *)timer {
	(void)timer;
	if (!auto_format_default)
		return;

	@autoreleasepool {
		NSPasteboard *pboard = [NSPasteboard generalPasteboard];
		NSInteger cur_change = [pboard changeCount];
		if (cur_change != last_change) {
			last_change = cur_change;
			char *html = NULL;
			size_t len = 0;
			if (clipboard_read_html(&html, &len) == 0 && html && len > 0) {
				process_html_to_clipboard(html, len, &current_cfg);
				last_change = [pboard changeCount];
				free(html);
			}
		}
	}
}

- (void)actionPasteActive:(id)sender {
	(void)sender;
	clipboard_paste_active(&current_cfg);
}

- (void)toggleAutoFormat:(id)sender {
	(void)sender;
	auto_format_default = !auto_format_default;
	[self buildMenu];
}

- (void)setModePlain:(id)sender { (void)sender; current_cfg.mode = MODE_PLAIN; [self buildMenu]; }
- (void)setModeMarkdown:(id)sender { (void)sender; current_cfg.mode = MODE_MARKDOWN; [self buildMenu]; }
- (void)setModeTerminal:(id)sender { (void)sender; current_cfg.mode = MODE_TERMINAL; [self buildMenu]; }
- (void)setTableGrid:(id)sender { (void)sender; current_cfg.table_style = TABLE_STYLE_GRID; current_cfg.unicode_tables = 0; [self buildMenu]; }
- (void)setTableUnicode:(id)sender { (void)sender; current_cfg.table_style = TABLE_STYLE_GRID; current_cfg.unicode_tables = 1; [self buildMenu]; }
- (void)setTableMarkdown:(id)sender { (void)sender; current_cfg.table_style = TABLE_STYLE_MARKDOWN; [self buildMenu]; }
- (void)setTableTsv:(id)sender { (void)sender; current_cfg.table_style = TABLE_STYLE_TSV; [self buildMenu]; }

- (void)setLangAuto:(id)sender {
	(void)sender;
	i18n_set_language(LANG_AUTO);
	[[NSUserDefaults standardUserDefaults] removeObjectForKey:@"Language"];
	[self buildMenu];
}

- (void)setLangEn:(id)sender {
	(void)sender;
	i18n_set_language(LANG_EN);
	[[NSUserDefaults standardUserDefaults] setObject:@"en" forKey:@"Language"];
	[self buildMenu];
}

- (void)setLangEs:(id)sender {
	(void)sender;
	i18n_set_language(LANG_ES);
	[[NSUserDefaults standardUserDefaults] setObject:@"es" forKey:@"Language"];
	[self buildMenu];
}

- (void)toggleStartup:(id)sender {
	(void)sender;
	set_launch_agent_enabled(!is_launch_agent_enabled());
	[self buildMenu];
}

- (void)showAbout:(id)sender {
	(void)sender;
	NSAlert *alert = [[NSAlert alloc] init];
	[alert setMessageText:[NSString stringWithUTF8String:i18n_get(STR_ABOUT_TITLE)]];
	[alert setInformativeText:[NSString stringWithUTF8String:i18n_get(STR_ABOUT_BODY)]];
	[alert setAlertStyle:NSAlertStyleInformational];
	[alert addButtonWithTitle:@"OK"];
	[alert runModal];
}

- (void)quitApp:(id)sender {
	(void)sender;
	[NSApp terminate:nil];
}

@end

int
clipboard_watch(const struct config *cfg)
{
	if (cfg) {
		current_cfg = *cfg;
	} else {
		memset(&current_cfg, 0, sizeof(current_cfg));
		current_cfg.mode = MODE_PLAIN;
	}

	@autoreleasepool {
		NSApplication *app = [NSApplication sharedApplication];
		ClipBridgeAppDelegate *delegate = [[ClipBridgeAppDelegate alloc] init];
		[app setDelegate:delegate];
		[app run];
	}
	return 0;
}

#else
typedef int iso_c_dummy_clipbridge_macos;
#endif /* __APPLE__ */
